app:
    resource: "@CompanyBundle/Controller/"
    type:     annotation
    prefix:   /crm


fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix:   /

root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: "http://localhost/index.html"
        permanent: true




