domain:
    resource: "@DomainBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@CompanyBundle/Controller/"
    type:     annotation
    prefix:   /crm


fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix:   /






