company:
    resource: "@CompanyBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix:   /

app:
    resource: "@CompanyBundle/Controller/"
    type:     annotation
    prefix:   /crm



