# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
            ROLE_ADMIN:       ROLE_USER
            ROLE_SUPER_ADMIN: ROLE_ADMIN

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
            fos_userbundle:
                id: fos_user.user_provider.username_email

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            logout:
                path: /crm/logout
                target: /crm/login
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                login_path: /crm/login
                check_path: /crm/login_check
                default_target_path: /crm

            remember_me:
                secret: '%secret%'
                lifetime: 604800    # one week in seconds


    access_control:
            - { path: ^/crm/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/crm/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/crm/, roles: [ROLE_USER, ROLE_ADMIN, ROLE_SADMIN] }
            - { path: ^/crm/profile/*, roles: [ROLE_ADMIN, ROLE_SADMIN] }